API_TOKEN = "8511008734:AAGaxwKQYQAFQD-EFRCp5IbpNf-Uxt91NYI"
LZT_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOjYyOTA2MzYsImlzcyI6Imx6dCIsImlhdCI6MTc3MzA1NjA5NSwianRpIjoiOTQyODc3Iiwic2NvcGUiOiJiYXNpYyByZWFkIHBvc3QgY29udmVyc2F0ZSBwYXltZW50IGludm9pY2UgY2hhdGJveCBtYXJrZXQiLCJleHAiOjE5MzA3MzYwOTV9.jlblZrWa3It7WhjUg9z6b76VflvndvIiuBgysN56LFJnQar6xVD9_HwZ9dgUSlFpqTffCcp3jeIqQBofOoyu2JTNKD-iBeeo6-lwxmK-HP-_RSnbf5aybkyKUqdh7d6bFbbGfn-9dE-dBvdPjMUs00bTbQ-wGDdKJzQrit6PO5I"

# URL категории miHoYo
LZT_URL = "https://api.lzt.market/category/mihoyo?sort_by=date&order=desc"

# Интервал проверки новых лотов (в секундах)
CHECK_INTERVAL = 5
